//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bills
    {
        public int id { get; set; }
        public string med { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> patientId { get; set; }
        public Nullable<int> used { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
